### ISSUE TITLE
Open Issues feature to the public

### ISSUE THREAD

**Issue by biblepay** [biblepay/biblepay-evolution#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Borgholio** [comment]
With the new Funded ABN feature, it would be useful if when a normal miner burns through their own ABN, they can continue mining using the Funded ABN until they can build up their own sufficient ABN again.

**Comment by biblepay** [comment]
Hi Borg,  this was the 'new issue template' issue, so I transferred your issue to a new issue - please see the master issues list.

**Comment by biblepay** [comment]
Borg, can you please make a post in the new issue?
