### ISSUE TITLE
Superblock Payment shows matured but requires 102 confirmations

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#10]
Superblock payment currently has 12 confirmations.
Smart Contract reward current has 61 confirmations.

There's a checkmark icon next to the transaction even though it is still unconfirmed and requires 102 blocks to mature.

![image](https://user-images.githubusercontent.com/6989799/63949215-e4f3cc80-ca2e-11e9-8003-3f0f77716db6.png)

![Screenshot 2019-08-30 14 09 04](https://user-images.githubusercontent.com/6989799/64051624-8878d600-cb30-11e9-8ee4-39bf1f514239.jpg)

`Generated coins must mature 102 blocks before they can be spent. When you generated this block, it was broadcast to the network to be added to the block chain. If it fails to get into the chain, its state will change to "not accepted" and it won't be spendable. This may occasionally happen if another node generates a block within a few seconds of yours.`

**Comment by biblepay** [comment]
Ack - Fixing both issues in 1.4.4.6 - ETA 48 hours.

**Comment by sunk818** [comment]
Thanks, I see the correct icon now. Smart-Contract Reward

<img width="372" alt="Screenshot 2019-09-04 10 38 23" src="https://user-images.githubusercontent.com/6989799/64277926-613f5180-cf00-11e9-8b6b-1f349eb34430.png">
