### ISSUE TITLE
Suggest to allow exec roi include custom bbp amounts: exec roi <bbpamount>

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#11]
Does the `exec roi` currently use `pog_ coinagepercentage` value in `biblepay.conf` to determine the roi?

akkin4 waited 7 days like skillrex does, then tithed 1k BBP. He got back 800 BBP. He is discouraged from participating in PoG because he feels it is for whales only and he must spend $2k-$3k USD to participate successfully. I think many feel there's a high bar to participate.

`exec roi 10` might help BBP investors to at least see how many points a tithe of 10 will generate for PoG. It doesn't prevent skillrex, inblue, or any other member with coinage from sniping once a week, but points is a metric that will not change once you tithe. Owed and prominence is a moving target and thus "profitable" is just not guaranteed.

**Comment by biblepay** [comment]
1) 'exec roi' does not currently honor the pog coinagepercentage - which appears to be a problem.  It currently uses all of the wallets coin age for the simulation.
2) exec roi <bbpamount> sounds like a good idea.

I will add #2 in and fix #1 for now.

**Comment by sunk818** [comment]
Makes me also wonder if the owed amounts reflect the change in the GSC payouts after POOm got enacted?

**Comment by biblepay** [comment]
Yes, exec roi uses the actual POG budget already.

**Comment by biblepay** [comment]
Ok this has been added, lets test it in 1449.

**Comment by sunk818** [comment]
Well done, thank you.
