### ISSUE TITLE
Campaign owed amounts are for next range not what Leaderboard v1.0 states

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#15]
It seems for the GSC campaign Healing for [block 145160](https://chainz.cryptoid.info/bbp/tx.dws?97303c6c33d0bf2ffdc17483e10c74328bcb0f959123a24585580568cac49023.htm
), Sakic received the bulk from the healing campaign 17k out of 19k BBP?

I put HEALING [144705](https://chainz.cryptoid.info/bbp/tx.dws?1138329.htm) and [144998](https://chainz.cryptoid.info/bbp/tx.dws?1139210.htm).

I was thinking rather than 6k received today, it would have been 6k POOM and 4k HEALING = 10k BBP.

---

Edit: 9/16/2019

I think I got confused by Leaderboard v1.0 Range. It currently says 153365 to 145570, but really the leaderboard values (owed and prominence) are not for that range, but the next range after that (145570-145685).

_It is also not clear if you tithe is in the Smart-Contract Reward, which block range it is valid for. I ask because in one range the end range is 145570 and in the next range the start is 145570._

> xx:x1:26		leaderboard true 145365
> xx:x1:26		{
>   "Prominence": "Details",
>   "CAMEROON-ONE: xx[Sunk], Pts: 4000.00": "1.91%",
>   "HEALING: xx[Sunk], Pts: 9239505.00": "1.93%",
>   "POG: xx[Sunk], Pts: 0.00": "0.00%",
>   "Healing": "Diary Entries",
>   "RubeGold": "xx",
>   "Prominence": "Totals",
>   "ALL: xx[RubeGold], Pts: 9243505.00, Reward: 13047.260": "3.830%"
> }
> xx:x2:03		leaderboard true 145160
> xx:x2:04		{
>   "Prominence": "Details",
>   "CAMEROON-ONE: xx [Sunk], Pts: 4000.00": "1.91%",
>   "HEALING: xx [Sunk], Pts: 7155200.00": "1.29%",
>   "POG: xx [Sunk], Pts: 0.00": "0.00%",
>   "Healing": "Diary Entries",
>   "RubeGold": "xx",
>   "Prominence": "Totals",
>   "ALL: xx [RubeGold], Pts: 7159200.00, Reward: 10877.110": "3.200%"
> }
> xx:x2:37		leaderboard true 144955
> xx:x2:37		{
>   "Prominence": "Details",
>   "CAMEROON-ONE: xx [Sunk], Pts: 4000.00": "1.91%",
>   "HEALING: xx [Sunk], Pts: 0.00": "0.00%",
>   "POG: xx [Sunk], Pts: 0.00": "0.00%",
>   "Healing": "Diary Entries",
>   "Prominence": "Totals",
>   "ALL: xx [RubeGold], Pts: 4000.00, Reward: 6488.920": "1.910%"
> }
>

**Comment by sunk818** [comment]
I think I got confused by Leaderboard v1.0 Range. It currently says 153365 to 145570, but really the leaderboard values (owed and prominence) are not for that range, but the next range after that (145570-145685).

It is also not clear if you tithe is in the Smart-Contract Reward, which block range it is valid for. I ask because in one range the end range is 145570 and in the next range the start is 145570.

`xx:x1:26		leaderboard true 145365
xx:x1:26		{
  "Prominence": "Details",
  "CAMEROON-ONE: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 4000.00": "1.91%",
  "HEALING: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 9239505.00": "1.93%",
  "POG: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 0.00": "0.00%",
  "Healing": "Diary Entries",
  "RubeGold": "xx",
  "Prominence": "Totals",
  "ALL: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [RubeGold], Pts: 9243505.00, Reward: 13047.260": "3.830%"
}
xx:x2:03		leaderboard true 145160
xx:x2:04		{
  "Prominence": "Details",
  "CAMEROON-ONE: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 4000.00": "1.91%",
  "HEALING: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 7155200.00": "1.29%",
  "POG: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 0.00": "0.00%",
  "Healing": "Diary Entries",
  "RubeGold": "xx",
  "Prominence": "Totals",
  "ALL: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [RubeGold], Pts: 7159200.00, Reward: 10877.110": "3.200%"
}
xx:x2:37		leaderboard true 144955
xx:x2:37		{
  "Prominence": "Details",
  "CAMEROON-ONE: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 4000.00": "1.91%",
  "HEALING: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 0.00": "0.00%",
  "POG: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 0.00": "0.00%",
  "Healing": "Diary Entries",
  "Prominence": "Totals",
  "ALL: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [RubeGold], Pts: 4000.00, Reward: 6488.920": "1.910%"
}
`

**Comment by biblepay** [comment]
- I just modified 1.4.4.9 to show the correct range on the UI leaderboard banner.  Its supposed to be the *next* superblock height, up to that height + BLOCKS_PER_DAY - 1.

So let me know if we have more than 1 issue - other than this.

**Comment by sunk818** [comment]
Block currently 147505.

Leaderboard block range seems to be correct now.

![image](https://user-images.githubusercontent.com/6989799/65732957-189f3200-e081-11e9-9002-cf8e7995a209.png)
