### ISSUE TITLE
Command 'sendgscc' help still refers to 'exec sendgscc'

### ISSUE THREAD

**Issue by oncoapop** [biblepay/biblepay-evolution#18]
>cli sendgscc

Output:
error code: -1
error message:
You must specify sendgscc campaign_name [foundation_donation_amount] [optional:diary_entry] : IE 'exec sendgscc healing 10 ["prayed for Jane Doe who had broken ribs, this happened"].

>cli exec sendgscc
{
  "Command": "sendgscc",
  "Error": "Command not found"
}

cli --version
BiblePay Core RPC client version 1.4.6.3

**Comment by sunk818** [comment]
@oncoapop hello, I put in a pull request so the edited help text can be merged in at Rob's convenience.

**Comment by biblepay** [comment]
Will be fixed in the next build.

Please use 'sendgscc'.
