### ISSUE TITLE
Wallet Error

### ISSUE THREAD

**Issue by N8Thrasher** [biblepay/biblepay-evolution#2]
Desktop Wallet opened for a while and mining for a couple of minutes then Wallet report error and close.

![Capture](https://user-images.githubusercontent.com/24593637/61121898-12011580-a4a9-11e9-92e9-f1c1b866be5f.PNG)

OS: WIn 7 64bit
CPU: i7 4790k
Latest wallet BiblePay Core version 1.4.4.1 (64-bit)

biblepay.conf:

```
addnode=explorer.biblepay.org
genproclimit=4
gen=1
tithing=1
pool=https://pool.biblepay.org
workerid=yey
maxconnections=8
minersleep=0
```

**Comment by N8Thrasher** [comment]
changed genproclimit to 2 solve the issue, been running for more than 30 minutes and error dont show up anymore.

**Comment by biblepay** [comment]
Debugging now...

**Comment by biblepay** [comment]
Thrasher,

Can you please try 1.4.4.1h:
Windows 32/64 has been deployed.


https://github.com/biblepay/biblepay-evolution/commit/be9675fa4a8970ff8ee63cb7fdda035a545b7c13


Note:  We have not deployed linux or mac yet.

Thanks.
