### ISSUE TITLE
PoG donation being attempted (?) even though it is turned off in biblepay.conf

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#24]
Even though I turned off pog donations, I debug is saying it tried to tithe 1 BBP.

these are my biblepay.conf settings in 1.4.4.9

```
# gsc
disablegsctransmission=0
pog_coinagepercentage=-1
pog_foundationdonation=-1
healing_coinagepercentage=0.9999
healing_foundationdonation=2
cameroon-one_coinagepercentage=0.0001
cameroon-one_foundationdonation=2
gscclientminerfrequency=6048000
```

I tried to submit a sendgscc healing 777 "prayer"

In the Debug Console, the reply is:

```
{
  "Error!": "CreateGSCTransmission::Fail::(Create Transaction) Insufficient funds.",
  "Error!": "HEALING: CreateGSCTransmission::Fail::(Create Transaction) Insufficient funds."
}
```
In the debug.log file, I see another message that says:

`SmartContract-Client::Creating Client side transaction for campaign HEALING 
CreateGSCClientTransmission - Total Bal 7734046.003946, Needed 7504576.747517, Coin-Age 5983439.716690, Target-Spend-Pct 0.990000, FoundationDonationAmount 1.000000  Donating 1.000000 to the foundation. 
Created client side transmission - <MT>GSCTransmission</MT><abnmsg>,,,</abnmsg><gscsig>,,,</gscsig><abncpk>BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU</abncpk>
<gsccampaign>HEALING</gsccampaign><abnwgt>5923605</abnwgt>
<diary>prayer</diary> [] with txid 0000000000000000000000000000000000000000000000000000000000000000 
Tithing 1.000000 BBP into the Orphan Foundation for POG, because expected ROI is 18979.310718 percent.Loading addresses from DNS seeds (could take a while)
`

Edit: I waited 30 minutes, restarted wallet, tried again and it went through this time.

**Comment by biblepay** [comment]
1) The "Insufficient funds" message occurs when the depth of your available coins are < 6.  That explains why your healing was not sent.

2) The Foundation Donation amount = 1 most likely occurred because your biblepay.conf settings were not read (either you had the wrong delimiter in the file, or you didnt reboot after changing them).

I assume everything is working correctly now that you have rebooted; why no positive update on this?

**Comment by sunk818** [comment]
> 1. The "Insufficient funds" message occurs when the depth of your available coins are < 6.  That explains why your healing was not sent.

At the time, some of my coins were older than 6 confirms, but I'm guessing if the `coinagepercentage` value is set too high  (e.g. 0.999) then there is a conflict and I will get this error. Is there a good reason to not allow coins >= 1 confirm to be included? If it is for security reason, that's fine. I understand how gsc tithing works, so I'll know for the future. Thanks!
