### ISSUE TITLE
Suggestion: Divide points column by 1,000

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#27]
I think points column will be easier to read if **points** became **kpoints**.

Bonus if you make the thousands separator a space.

For example 3,590,270,595 (3.5 billion) reads 3 590 270

![image](https://user-images.githubusercontent.com/6989799/66366572-bdedbc00-e945-11e9-847d-fe58ef68b4f6.png)

Bonus bonus if all number columns are right justified.

**Comment by biblepay** [comment]
Good idea.

**Comment by sunk818** [comment]
Working good. Looks much better. Thanks for the updated code!

![image](https://user-images.githubusercontent.com/6989799/67963830-7c56d680-fbbc-11e9-9e6e-e246e547638b.png)

**Comment by sunk818** [comment]
Looks like these changes got reverted in 1.4.8.4

**Comment by biblepay** [comment]
We no longer have POG.
