### ISSUE TITLE
Allow dual non-abn(Turnkey)/ABN mining in biblepaycore 

### ISSUE THREAD

**Issue by biblepay** [biblepay/biblepay-evolution#3]
With the new Funded ABN feature, it would be useful if when a normal miner burns through their own ABN, they can continue mining using the Funded ABN until they can build up their own sufficient ABN again.

**Comment by biblepay** [comment]
Borg, are you available to test this?

**Comment by Borgholio** [comment]
Sure, what do I need to do?

**Comment by biblepay** [comment]
@Borgholio Awesome, so just follow this:
https://bitcointalk.org/index.php?topic=2388064.msg51809868#msg51809868

So far, Only windows has been deployed (to keep the scope limited).  Let us know if you need Linux built and I would need to pass that request over to MIP.

**Comment by Borgholio** [comment]
Ok I set up one funded and one non-funded user ID in the pool.  I currently have enough funds to never run out of ABN so I'll test in stages.  I'll let it run normally and transfer some funds out so it dips into the funded worker and see how that works.

**Comment by biblepay** [comment]
Looks like this is working for everyone in the pool, so I believe its safe to close now, thank you for testing!
