### ISSUE TITLE
sponsorchild authorize out of date

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#30]
With the `exec paycameroon childid 40 test` feature, the notes in `sponsorchild authorize` seems out of date in the Notes.

Payment via BBP is easiest and most transparent. I feel BBP should be the first recommended payment method, with the other ones being secondary. 

> 20:01:24 sponsorchild authorize
> 20:01:24￼
> {
>   "Results": true,
>   "Notes 0": "Thank you for sponsoring a child through Cameroon One. ",
>   "Notes 1": "Your new child ID is: 1dc6f6b0",
>   "Notes 2": "NOTE: You will not receive rewards for this child until Cameroon One posts a credit to your account for this child.  ",
>   "Notes 3": "It can take 7-14 days to provision a new child, receive and post your payment, so please, be patient. ",
>   "Notes 4": "To check the status of your child, type 'listchildren' into the RPC.",
>   "Notes 5": "Option 1:  Please mail a check for $40.00 (this is a tax deductible donation) to:",
>   "Notes 6": "Cameroon One A/R",
>   "Notes 7": "28 Hawthorne St Unit 1",
>   "Notes 8": "Boston, MA 02119 USA",
>   "Notes 9": "!NOTE! You must write Child ID #1dc6f6b0 on your check.",
>   "Notes 10": "Option 2: [Preferred] For the most efficient/fastest credit use PayPal (accepting Credit Cards and international payments):",
>   "Notes 11": "PayPal: Send money to https://PayPal.Me/CameroonONE ",
>   "Notes 12": "NOTE: Please paste the BiblePay hex child ID #1dc6f6b0 in the Paypal NOTES textbox before submitting the payment.",
>   "Notes 13": "Option 3:  GlobalGiving Match:",
>   "Notes 14": "To use Global Giving, see this page https://www.globalgiving.org/recurring-donations-matched/ and set up a recurring donation, then notify Anna with CameroonONE <xxx@cameroonone.org> with your ChildID and verify the recurring donation is set up.",
>   "Notes 15": "Option 4:  Pay in BBP:",
>   "Notes 16": "To pay with BiblePay, send the converted amount (based on the midpoint of our coinmarketcap value) to Cameroon-One's wallet: BF6qmwBMmnmb4FbSmRGTeWQL1m3rwh5n7b",
>   "Notes 17": "Then send an e-mail to 'Todd <xxx@cameroonone.org>' with the BBP Amount sent, the TXID, and the Child ID you are paying for.",
>   "Notes 18": ""
> }
>

**Comment by biblepay** [comment]
The most recent code is actually in develop, so we should be basing our assessments on that branch (not on this branch) as that has the most recent changes.

In that branch we have a designated output per charity pointing to their wiki page now.
