### ISSUE TITLE
Fix -reindex=1 

### ISSUE THREAD

**Issue by biblepay** [biblepay/biblepay-evolution#7]
We need to either fix reindex, or if we cant due to compact blocks and max serialization size, ensure gov and dat and SAN files get erased so they resync.

**Comment by sunk818** [comment]
Seems like `--erasechain` is a good replacement for `-reindex`. Can you make `-reindex` an alias of `--erasechain`?

**Comment by biblepay** [comment]
We are looking into it in the next version - MIP is first going to try to fix reindex, MIP please update if that is futile, and if futile I can potentially make erasechain work in reindex.

Especially since next quarter we will have the one click resync option also.

**Comment by MIPPL** [comment]
I will check it and see if it’s futile or not.

**Comment by MIPPL** [comment]
I discovered that miner thread starts before reindexing has finished, which causes a ProcessNewBlock call that overwrites and corrupts the block database. If I suspend the miner thread while reindexing is active, it does not crash any more. 

I will double check the solution with Rob and push it if valid.

**Comment by MIPPL** [comment]
Solved on dev branch
