### ISSUE TITLE
Proof of Giving (PoG) - Suggest max coin age to 1 day

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#8]
Proof of Giving payout is less predictable because some users are using coin age older than 1 day. They are intentionally saving up multiple days to earn a bigger reward. The payout for other participants is less predictable.

I would like to suggest a max coin age of 1 day regardless of the coin age submitted.

**Comment by biblepay** [comment]
I think its important to allow small users to be able to save up coin age in order to stake in competition with the big dogs.

Capping coin age at one day is in effect removing age from the equation - thereby making the equation more of a lottery on who has the most balance on a given day.  This would decimate the small holders (they would receive zero in contrast to someone with a large balance) - which I think is unfair. 

Coin Age rewards those who are saving the biblepay and holding it - thats a valuable attribute.

Yes, people are saving up intentionally, and that is their right (to not tithe on a particular day).

I disagree that its "less predictable" - than what, mining?  I think its much more predictable - than most algorithms I can think of that order a list of users by reward per week.

**Comment by sunk818** [comment]
> I disagree that its "less predictable" - than what, mining?

The way it is currently designed, it is less predictable than setting a cap of coin age of 1 day because individuals save up and tithe at unknown intervals.

**Comment by biblepay** [comment]
Saying that miners can receive constant and consistent rewards by setting a cap, is equivalent to saying stock market intervention by the government (IE if Trump were to create a team to limit all stock sales to no more than $1000 per day per participant would decrease market volatility), yes that would be a true statement.   (But it doesn't make it the correct solution).

The question remains, how do we reward the little fish appropriately?

**Comment by sunk818** [comment]
I haven't thought of all the scenarios, so I'm open to the idea that this may not be the "correct" solution. How would you reward the "little fish appropriately"?

> because it destroys the algorithm to be a worthless one - one based on user balance

If you PoG tithe twice a day, it ends up being mostly based on a user's balance. I don't agree that makes the algorithm worthless -- it just places less emphasis and doesn't allow people to game PoG like they are now.

One user said: _Yes,the whale pog donation 20k and resive 200k next day,and i gave 3000 k and get 30 bbp back, ... ,so i quit big donation,couse i belive we small one pog to the whales not to the poor_

Whether the sentiment is correct, that's how at least one user feels. This BBP member likely doesn't fully understand how coin inputs and coin age works. These are difficult concepts to non-technical people, so it is not surprising...

Anyway, I think you can grow PoG participants if there is a way:

1) if you have predictable payouts, then this is easier to market. `exec roi` helps predict payout, but if someone saves up BBP for 7 days and tithes 27k out of 11M BBP, the `exec roi` ends up not reflecting what happens on the next payout. A smoother trend up or down will encourage participation. For example, with PoDC RAC took 14 days to build up so new RAC joining did not affect the daily payouts dramatically.

2) an incentive for friends to tell other friends about BBP (e.g. "little fish" encouraging other "little fish" to join). I think it is better to have lots of different people talking up BiblePay than a few whales. This is also why I suggested setting a max prominence (https://github.com/biblepay/biblepay-evolution/issues/9). You can ban people with multiple CPK right?

**Comment by biblepay** [comment]
Sun, please don't enter tickets to ask for consultation from the team, instead contact us directly and ask us for advice.

The ticket system is for feature requests and bugs.

The question should be rephrased as "I don't know how to solve this problem, but MIP or Rob, do you believe we have a problem in this area, and if so how would you recommend we solve it?"

Looking at the original post, I explained how removing age from coin*age ruins our algorithm and that I believe coin*age rewards the small fish as fairly as the large fish.

**Comment by sunk818** [comment]
> The ticket system is for feature requests

I made a feature request to cap the coin age to 1 day. It would be nice, but I don't expect you to agree.

**Comment by biblepay** [comment]
I pointed out why the idea is flawed; Again, its a flawed idea that would reduce POG down to a static richlist, decimating small users, and is not as fair as coin*age.  Small users can also save up coin_age, and that is what you are not taking into account.

If you think it all the way through and generate a model, and present an idea with substance we can open the case.  But a cap is not the answer.
