### ISSUE TITLE
Proof of Giving (PoG) - Suggest max prominence at 10%

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#9]
The top earnings seem to go to a few BBP holders. In order to encourage more members and to get the marketing word out, more participants is healthier than less. For that reason, I'd like to suggest a maximum prominence cap of 10%.

I've considered max input of 10M BBP but that could be bypassed with multiple GSC transmissions. Same with if someone wanted to create multiple separate wallets, but it does create some additional steps which someone may or may not want to do.

Anything past 10% prominence, could be alternatively invested toward sanctuaries or PoBH mining.

**Proverbs 19:17 NKJV**: He who has pity on the poor lends to the Lord, And He will pay back what he has given.
**Acts 20:35 NKJV**: I have shown you in every way, by laboring like this, that you must support the weak. And remember the words of the Lord Jesus, that He said, ‘It is more blessed to give than to receive.’ ”
**Hebrews 13:16 NKJV**: But do not forget to do good and to share, for with such sacrifices God is well pleased.

**Comment by biblepay** [comment]
I'd entertain this as a serious ticket if there was a solution given.

If we cap at 10% then people will start multiple CPKs.

Any comments before I close this?

(I read it as:  Lets cap those who own more than 10 sanctuaries in BBP at the reward level for 10 sancs).  It does not compute.
